### ISSUE TITLE
[Proposal] Consider to use AvaloniaEdit

### ISSUE THREAD

**Issue by timunie** [davidtimovski/json-formatter#1]
In order to improve performance for large files, consider to try [AvaloniaEdit](https://github.com/avaloniaui/avaloniaedit)

**Comment by davidtimovski** [comment]
Hello,

I am aware of AvaloniaEdit. It has been suggested to me previously as a solution to a problem in a different project but I didn't have much luck with it.

Feature-wise it's overkill. It's looks very old school, and it's hard to style and change because the docs are scarce. Well, the docs don't exist and the documentation of its parent AvalonEdit are more of a code reference than actual documentation. If I was using it, my perfect implementation of it in this project would contain only what's needed for formatting JSON and I'd be able to style it from scratch. But that's not how it works. It's fairly bloated and was obviously created to be a drop in code editor. In every other scenario it doesn't fit.

I'd prefer to dig into it and try and see how they achieve performant text formatting. If that becomes too low level for me I'll probably give up.

Thanks for the suggestion though, all info is valuable.
